### ISSUE TITLE
accept offer

### ISSUE THREAD

**Issue by dezet98** [InterPeteam/interpet-api#12]
W apce zaimplementowałem endpoint:
POST /offers/applications/{applicationId}/accept
Zwróciło mi kod 200, na swagerze także:
![image](https://user-images.githubusercontent.com/50755378/146259381-268370e0-7cf0-4e81-9390-c5dca59d1450.png)

ale w ofercie się chyba nic nie zmieniło:
![image](https://user-images.githubusercontent.com/50755378/146259468-8bcd6511-3a18-44c9-82cf-7a905744a9bc.png)

**Comment by nox12** [comment]
naprawiono
